In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2

In [3]:
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.15818485 0.39072686 0.31442743 ... 0.20625633 0.1517215  0.32925672]
 [0.24046825 0.80816927 0.83450637 ... 0.09968372 0.2326068  0.92763769]
 [0.19716337 0.49566614 0.11561501 ... 0.06472465 0.62322766 0.43129234]
 ...
 [0.64270348 0.28926184 0.97983293 ... 0.27830441 0.71506306 0.0084391 ]
 [0.82331112 0.60151864 0.89928795 ... 0.85969257 0.83347476 0.02139925]
 [0.71764878 0.86102801 0.32595423 ... 0.49779478 0.06928284 0.90658233]]
[[0.32373582 0.61949964 0.16021775 ... 0.38259197 0.51907479 0.80704462]
 [0.68637869 0.07494553 0.26519026 ... 0.42672667 0.16654573 0.20131243]
 [0.76527913 0.41218914 0.01886837 ... 0.04446345 0.86966327 0.27412015]
 ...
 [0.41939001 0.52822782 0.68875648 ... 0.25798684 0.87825627 0.32827841]
 [0.42846505 0.97666105 0.2064479  ... 0.58456044 0.85571212 0.30638172]
 [0.23934272 0.81520581 0.69477892 ... 0.42569887 0.4932962  0.7385842 ]]


In [4]:
# Без использования numpy
def mult(a, b):
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

In [5]:
# С использованием numpy
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 715 ms, sys: 1.67 ms, total: 716 ms
Wall time: 718 ms


In [7]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.71 ms, sys: 88 µs, total: 1.8 ms
Wall time: 4.32 ms


In [8]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.523758896837535e-11

In [9]:
#ЗАДАНИЕ 2
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.57478042 0.98301883 0.31148292] [0.81663238 0.32670639 0.1212358 ]


In [10]:
# Скалярное произведение без NumPy
def scalar_product(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

In [11]:
# Скалярное произведение с использованием NumPy
def np_scalar_product(a, b):
    return np.dot(a, b)

In [12]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 17 µs, sys: 2 µs, total: 19 µs
Wall time: 20.5 µs
CPU times: user 964 µs, sys: 955 µs, total: 1.92 ms
Wall time: 1.86 ms


0.0

Почему методы numpy оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?                                                                          
                                             
Ответ: NumPy обеспечивает высокую производительность благодаря своей внутренней реализации на языках C и Fortran, векторизации операций, использованию оптимизированных библиотек (например, BLAS и LAPACK), эффективному управлению памятью и поддержке параллелизма.

In [15]:
#ЗАДАНИЕ 3

def np_diag_2k(matrix):
    diagonal_elements = np.diag(matrix, k=0)
    even_diagonal_elements = diagonal_elements[::2]

    if even_diagonal_elements.size > 0:
        return np.sum(even_diagonal_elements)
    else:
        return 0

In [16]:
# Задаем некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))

In [17]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 106 µs, sys: 0 ns, total: 106 µs
Wall time: 110 µs


11

In [18]:
#ЗАДАНИЕ 4

def np_sec_av(*A):
    X = np.vstack(A)
    cumsum_matrix = np.cumsum(X, axis=1)
    row_indices = np.arange(1, X.shape[1] + 1)
    result = cumsum_matrix / row_indices[:, np.newaxis]
    return result

In [19]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.64072855 0.13513041 0.3489824  0.89679833 0.70243058 0.17636758
 0.31101919 0.32993663 0.96294707 0.40941508 0.34476219 0.93500818
 0.1897975  0.41230034 0.53234267 0.03819612 0.77235609 0.10022745
 0.68049738 0.32964791 0.35221618 0.87808911 0.39636442 0.82769084
 0.04945465 0.03377721 0.56724676 0.99741797 0.89189293 0.74189873
 0.22179057 0.8258892  0.2968301  0.48299386 0.1966482  0.18839288
 0.82294732 0.87511189 0.18505956 0.41036007 0.53656259 0.89321086
 0.24035322 0.19057029 0.13770794 0.23483286 0.45889636 0.30270669
 0.556583   0.9691147  0.27320091 0.07091463 0.95046242 0.00826333
 0.54721573 0.45308651 0.54597354 0.31745777 0.14957034 0.86748236
 0.53801902 0.8033932  0.81143854 0.14507212 0.75422003 0.83325948
 0.25831761 0.13764341 0.94608377 0.47179414 0.21266141 0.54731935
 0.24110696 0.44546608 0.66467687 0.89263114 0.41301176 0.05156292
 0.19665092 0.18510077 0.21606797 0.87566918 0.9811552  0.15234144
 0.68143593 0.03823783 0.64100214 0.0294328  0.55946898 0.8155

In [20]:
#ЗАДАНИЕ 5
def np_encode(a):
    grouped_data = [(key, len(list(group))) for key, group in groupby(a)]
    x, num = zip(*grouped_data)
    x = np.array(x)
    num = np.array(num)
    return x, num

In [23]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 0 ns, total: 51 µs
Wall time: 54.1 µs


In [24]:
#ЗАДАНИЕ 6
def np_transformation(X, a=1):
    result = X.copy()
    result[1::2] = a
    result[0::2] = result[0::2] ** 3
    result = result[::-1]
    final_result = np.concatenate((X, result))

    return final_result

In [27]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 1.1 ms
